[ci] Sort out handling of PRs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -112,17 +112,42 @@ jobs:
         # repo sibling of this snowball repo, so that PRs requiring changes to
         # both can be CI tested easily.
         #
-        # If that fails, just use the standard snowball-data repo's default
-        # branch.
-        git status
-        git remote -v
-        git show --no-patch "$GITHUB_REF_NAME"
-        env|sort
-        GH_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
-        GH_REPO_OWNER=${GITHUB_REPOSITORY_OWNER:-${GITHUB_REPOSITORY%%/*}}
-        GH_REPO_URL=https://github.com/$GH_REPO_OWNER/snowball-data.git
-        echo "Trying branch $GH_BRANCH from $GH_REPO_URL"
-        git clone --depth=1 -b "$GH_BRANCH" "$GH_REPO_URL" || { echo "Trying default branch from snowball/snowball-data"; git clone --depth=1 https://github.com/snowballstem/snowball-data.git; }
+        # For a PR, GHA will have merged the PR branch into upstream master so
+        # we need to similarly merge the snowball-data branch into upstream
+        # master of the snowball-data repo as there may be changes there
+        # required by snowball master.
+        #
+        # If there's no such branch (or repo) we just use the standard
+        # snowball-data repo's default branch.  If there is such a branch but
+        # the merge fails, we treat that as a fatal error.
+        UPSTREAM_REPO_URL=https://github.com/snowballstem/snowball-data.git
+        if [ -n "$GITHUB_HEAD_REF" ] ; then
+          # Pull-request.
+          GH_BRANCH=${GITHUB_HEAD_REF}
+          GH_REPO_OWNER=${GITHUB_ACTOR}
+          GH_REPO_URL=https://github.com/$GH_REPO_OWNER/snowball-data.git
+          git clone "$UPSTREAM_REPO_URL"
+          cd snowball-data
+          git remote add pr "$GH_REPO_URL"
+          git config --global user.email "ci@example.org"
+          git config --global user.name "CI"
+          echo "Trying branch $GH_BRANCH from $GH_REPO_URL"
+          if git fetch pr && git branch --track "$GH_BRANCH" pr/"$GH_BRANCH" ; then
+            git merge "$GH_BRANCH"
+          else
+            echo "Falling back to $UPSTREAM_REPO_URL"
+          fi
+        else
+          # Push.
+          GH_BRANCH=${GITHUB_REF_NAME}
+          GH_REPO_OWNER=${GITHUB_REPOSITORY_OWNER}
+          GH_REPO_URL=https://github.com/$GH_REPO_OWNER/snowball-data.git
+          echo "Trying branch $GH_BRANCH from $GH_REPO_URL"
+          if ! git clone -b "$GH_BRANCH" "$GH_REPO_URL" ; then
+            echo "Falling back to $UPSTREAM_REPO_URL"
+            git clone "$UPSTREAM_REPO_URL"
+          fi
+        fi
     - name: Install CCache
       uses: hendrikmuhs/ccache-action@v1
       with:
